### ISSUE TITLE
Allow to get VM zerotier IP from the info action

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/digital_me#20]
When we have the zerotier client configure with a token to talk to the zerotier IP. the info action of the VM template should also return the IP of the VM in the zerotier network.

If there is not zerotier client configured, just say that yo can't get the IP

**Comment by islamTaha12** [comment]
![image](https://user-images.githubusercontent.com/17981089/42579078-c7ce819c-8527-11e8-8a8c-22aeb582e119.png)
