### ISSUE TITLE
GW template is not authorizing the join request to the private ZT

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/digital_me#29]
![screen shot 2018-07-05 at 11 37 28](https://user-images.githubusercontent.com/13795109/42315509-ecb4edb4-8047-11e8-8042-ea9c54bc46dc.png)

![screen shot 2018-07-05 at 11 31 13](https://user-images.githubusercontent.com/13795109/42315521-f50e7a0c-8047-11e8-96a6-44d62d18f68f.png)

**Comment by yveskerwyn** [comment]
When reproducing this problem today, I had to authorize the join request manually, and once done the last call returned as expected; so no time out

So problem is still described in the title, the authorization doesn't work.

**Comment by yveskerwyn** [comment]
I'm suspecting/guessing that this problem is related to issue #32

**Comment by islamTaha12** [comment]
I can confirm it does now.
