### ISSUE TITLE
templates for VM

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/digital_me#3]
This template is going to be responsible to create a VM on a zero-os node. Which means this template will create a VM service using `zero-os/0-templates/vm`
Now, since this template is going to be used by end user, it needs to hides the small technicalities of the `zero-os/0-templates/vm` template. 
Also we should start to think in term of reservation, so for the DM robot, ordering a VM is about reserving some capacity (CPU,Memory,Disk,..)
Adding a disk to a VM involves to deal with zero-db services on the node too. So this templates will also need to deal with `zero-os/0-temlates/zerodb` 

Then we need to think about the possible action possible once the VM is created, these action will basically use the VM proxy service to schedule action on the node robot

### Proposed schema:
```capnp
@0xb87ba7e9ff3d95db;

struct Schema {
    memory @0: UInt16 = 128; # Amount of memory in MiB
    cpu @1: UInt16 = 1; # Number of virtual CPUs
    image @2: Image; # what image to boot
    ports @3:List(Text); # List of node to vm port mappings. e.g: 8080:80
    zerotierID @4: Text; # if specified, make the VM join the zerotier ID
    disks :List(Disk); # list of disk to attach to the VM
    configs @5: List(Config); # list of config

    enum Image{
        ubuntu @0;
        zeroos @0;
    }

    struct Disk{
        type @0 :DiskType;
        size @1 :UInt16; # size of the disk in GB
        mountpoint @2 :Text; # if specifed, where to mount the disk in the filesystem of the VM
        fsType @4 :FsType; # is specified, will format the disk with the select filesystem before mounting it
    }

    enum DiskType {
        hdd @0;
        ssd @1;
    }

    enum FsType {
        btrfs @0;
        ext4 @1;
        ext3 @2;
        ext2 @3;
    }

    struct Config {
        path @0: Text;
        content @1: Text;
    }
}

```

**Comment by islamTaha12** [comment]
I verified all the vm actions
https://github.com/Jumpscale/digital_me/tree/master/templates/vm#actions
