### ISSUE TITLE
find_or_create method returns error in case of the service is exising

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/digital_me#36]
![image](https://user-images.githubusercontent.com/17981089/42462828-af7b0270-83a4-11e8-8e98-6aec5d623408.png)

**Env**
zOS: 1.4.1
0-robot: development
0-dm: master
0-template: developmet
js9: dev

**Comment by zaibon** [comment]
@islamTaha12 please move this to 0-robot repository
