### ISSUE TITLE
templates for 0-OS gateway 

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/digital_me#4]
This template is going to be used by end-user so it needs to hide the technicalities of `zero-os/0-templates/gateway` template.

Also since this is supposed to be used by end user, we should probably provide some action to easily create some Cloudspace alike setup between VMs.
Under the hood, this template will have to deal with proxies to VMs and gateway services on the node robot

**Comment by zaibon** [comment]
Proposed interface of the template:

- `install`: creates a gateway on a node, starts it and configures all services
- `start`: start a gateway
- `stop`: stops a gateway
- `add_portforward`: Adds a portforward to the firewall
- `remove_portforward`: Removes a portforward from the firewall
- `add_http_porxy`: Adds a httpproxy to the http server
- `remove_http_porxy`: Removes a httpproxy from the http server
- `add_network`: Adds a network to the gateway
- `remove_network`: Remove a network from the gateway
- `info`: Retreive information about your gateway
- `add_public_forward`: create a port forward through the public gateway so service on a VM can be reachable from public internet
- `remove_public_forward`: remove a public port forward
- `add_public_http_proxy`: create a reverse proxy through the public gateway so service on a VM can be reachable from public internet
- `remove_public_http_proxy`: remove a public http proxy

**Comment by grimpy** [comment]
I deviated a bit from these specs in my work.
I disliked the concept of public and not public forward/http proxies.
I decided to make it more transparent for the enduser when he adds a forward or http proxy I setup the required forwards in both gateway hiding the complexity of dealing with 2 gateways.

Currently progress can be found at https://github.com/Jumpscale/digital_me/tree/gw
so far only tcpforwars are implemented and tested.

**Comment by islamTaha12** [comment]
![image](https://user-images.githubusercontent.com/17981089/42585092-03356e1e-8535-11e8-8aa3-7b5b38f6de2b.png)

all of these actions are working fine but only `add_network` doesn't authorize the GW 
https://github.com/Jumpscale/digital_me/issues/38
